Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 80
AllCops:
  Exclude:
    - '**/sorbet'
StringLiterals:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/MethodLength:
  Max: 7